apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-tq5i
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0003-tenant/tkrw-pr712-0075-0003-app/devfile-sample-tq5i@sha256:938f60ddfac608faaeb4ae2cc564aed5d6326e9197fd01f2de2b92ccd5323724
        name: my-nodejs
        resources: {}
status: {}
